kind: Deployment
apiVersion: apps/v1
metadata:
  name: b1-prod
spec:
  replicas: 
  selector:
    matchLabels:
      app: b1
      env: prod
  template:
    metadata:
      name: b1
      labels:
        app: b1
        env: prod
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: b1
          image: quay.io/robinwu456/alpine.httpd:1.0.0
          imagePullPolicy: Always
